/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domain.Carro;
import domain.Estacionamento;
import domain.Moto;
import domain.Veiculo;
import exceptions.CampoVazioException;
import exceptions.LimiteAtingidoException;
import exceptions.VeiculoRepetidoException;
import java.util.ArrayList;
import services.ArquivoVeiculos;

/**
 *
 * @author marcusz
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private Estacionamento estacionamento = new Estacionamento();
    private ArrayList<Veiculo> veiculos = new ArrayList<>();
    private ArquivoVeiculos arquivo = new ArquivoVeiculos();

    /**
     * Creates new form Janela
     */
    public TelaPrincipal() {
        initComponents();
        veiculos = arquivo.listarTodas();
        for (Veiculo v : veiculos) {
        estacionamento.getVeiculos().add(v);
        }
        buttonRemover.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textModelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboVeiculo = new javax.swing.JComboBox<>();
        buttonRegister = new javax.swing.JButton();
        labelErro = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        panelConsultar = new javax.swing.JPanel();
        fieldPlacaConsulta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelPlaca = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        labelProprietario = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelErroConsulta = new javax.swing.JLabel();
        buttonSair1 = new javax.swing.JButton();
        panelRemover = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelPlacaRemocao = new javax.swing.JLabel();
        labelModeloRemocao = new javax.swing.JLabel();
        labelProprietarioRemocao = new javax.swing.JLabel();
        labelTipoRemocao = new javax.swing.JLabel();
        buttonRemover = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        fieldPlacaRemocao = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        labelResultadoRemocao = new javax.swing.JLabel();
        labelErroRemocao = new javax.swing.JLabel();
        buttonSair2 = new javax.swing.JButton();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estacionamento condominial");

        jTabbedPane1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Nome proprietário:");

        textNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        textPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Placa:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Modelo:");

        textModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel8.setText("Veiculo:");

        comboVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRO", "MOTO" }));
        comboVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVeiculoActionPerformed(evt);
            }
        });

        buttonRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonRegister.setText("REGISTRAR");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        buttonSair.setText("SAIR");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        panelRegistroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboVeiculo, textModelo, textNome, textPlaca});

        panelRegistroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel8});

        panelRegistroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonRegister, buttonSair});

        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVeiculo)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelErro))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSair)
                .addGap(34, 34, 34))
        );

        panelRegistroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboVeiculo, textModelo, textNome, textPlaca});

        panelRegistroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel8});

        panelRegistroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonRegister, buttonSair});

        jTabbedPane1.addTab("Registrar veiculo", panelRegistro);

        jButton1.setText("CONSULTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Digite a placa do veiculo que deseja buscar:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setText("Placa:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setText("Modelo:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setText("Proprietário:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel10.setText("Tipo:");

        labelPlaca.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        labelModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelProprietario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonSair1.setText("SAIR");
        buttonSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSair1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultarLayout = new javax.swing.GroupLayout(panelConsultar);
        panelConsultar.setLayout(panelConsultarLayout);
        panelConsultarLayout.setHorizontalGroup(
            panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelErroConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelConsultarLayout.createSequentialGroup()
                            .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelProprietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelConsultarLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldPlacaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonSair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panelConsultarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelModelo, labelPlaca, labelProprietario, labelTipo});

        panelConsultarLayout.setVerticalGroup(
            panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultarLayout.createSequentialGroup()
                        .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(labelModelo))
                        .addGap(6, 6, 6)
                        .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(labelProprietario))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addGroup(panelConsultarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(labelTipo)))
                .addGap(41, 41, 41)
                .addComponent(labelErroConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldPlacaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSair1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar veiculo", panelConsultar);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel12.setText("Placa:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel13.setText("Modelo:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel15.setText("Proprietário:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel16.setText("Tipo:");

        labelPlacaRemocao.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        labelModeloRemocao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelProprietarioRemocao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelTipoRemocao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonRemover.setText("REMOVER");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Digite a placa do veiculo que deseja buscar:");

        jButton4.setText("CONSULTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        buttonSair2.setText("SAIR");
        buttonSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSair2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRemoverLayout = new javax.swing.GroupLayout(panelRemover);
        panelRemover.setLayout(panelRemoverLayout);
        panelRemoverLayout.setHorizontalGroup(
            panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverLayout.createSequentialGroup()
                .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRemoverLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRemoverLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelTipoRemocao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelProprietarioRemocao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelModeloRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelRemoverLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelPlacaRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRemoverLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelRemoverLayout.createSequentialGroup()
                                .addComponent(labelResultadoRemocao)
                                .addGap(259, 259, 259))
                            .addComponent(labelErroRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRemoverLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldPlacaRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonSair2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelRemoverLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelModeloRemocao, labelPlacaRemocao, labelProprietarioRemocao, labelTipoRemocao});

        panelRemoverLayout.setVerticalGroup(
            panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPlacaRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(6, 6, 6)
                .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRemoverLayout.createSequentialGroup()
                        .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(labelModeloRemocao))
                        .addGap(6, 6, 6)
                        .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(labelProprietarioRemocao))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16))
                    .addGroup(panelRemoverLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(labelTipoRemocao)))
                .addGap(26, 26, 26)
                .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelResultadoRemocao)
                    .addComponent(labelErroRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldPlacaRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSair2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelRemoverLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelModeloRemocao, labelPlacaRemocao, labelProprietarioRemocao, labelTipoRemocao});

        panelRemoverLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonRemover, jButton4});

        jTabbedPane1.addTab("Remover veiculo", panelRemover);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void comboVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVeiculoActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        labelErro.setText("");
        try{
            if (textNome.getText().isEmpty() || textPlaca.getText().isEmpty() || textModelo.getText().isEmpty()){
                throw new CampoVazioException("Preencha todos os campos!");
            }
            for(Veiculo v: veiculos){
                if(v.getPlaca().equals(textPlaca.getText())){
                    throw new VeiculoRepetidoException("Veiculo ja está cadastrado!");
                }
            }
            Veiculo veiculo = null;
            if (comboVeiculo.getSelectedItem().equals("CARRO")) {
                veiculo = new Carro(textPlaca.getText(), textModelo.getText(), textNome.getText());
            } else {
                veiculo = new Moto(textPlaca.getText(), textModelo.getText(), textNome.getText());
            }
            
            estacionamento.cadastrarVeiculo(veiculo);
            veiculos.add(veiculo);
            arquivo.salvarReservas(veiculos);
            
            textPlaca.setText("");
            textModelo.setText("");
            textNome.setText("");
            
        }catch(CampoVazioException ex){
            labelErro.setText("É necessario preencher todos os campos.");
        }catch(VeiculoRepetidoException e){
            labelErro.setText("Veiculo com a placa "+textPlaca.getText()+" ja registrado!");
        }catch(LimiteAtingidoException el){
            labelErro.setText(el.getMessage());
        }
        
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean encontrado = false;
        labelPlaca.setText("");
        labelModelo.setText("");
        labelProprietario.setText("");
        labelTipo.setText("");
        labelErroConsulta.setText("");
       
        for(Veiculo v: veiculos){
            if(v.getPlaca().equals(fieldPlacaConsulta.getText())){
                encontrado = true;
                labelPlaca.setText(v.getPlaca());
                labelModelo.setText(v.getModelo());
                labelProprietario.setText(v.getProprietario());
                if(v instanceof Carro){
                    labelTipo.setText("CARRO");
                }else{
                    labelTipo.setText("Moto");
                }
            }
        }
        if(encontrado == false){
            labelErroConsulta.setText("Não encontramos o veiculo com placa: "+fieldPlacaConsulta.getText());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        Veiculo veiculoRemocao = null;
        labelResultadoRemocao.setText("");
        for(Veiculo v: veiculos){
            if(v.getPlaca().equals(fieldPlacaRemocao.getText())){
                veiculoRemocao = v;
            }
        }
        if(!(veiculoRemocao == null)){
            veiculos.remove(veiculoRemocao);
            arquivo.salvarReservas(veiculos);
            labelResultadoRemocao.setText("Veiculo removido com sucesso!");
            buttonRemover.setEnabled(false);
        } 
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boolean encontrado = false;
        labelPlacaRemocao.setText("");
        labelModeloRemocao.setText("");
        labelProprietarioRemocao.setText("");
        labelTipoRemocao.setText("");
        labelErroRemocao.setText("");
        
        for(Veiculo v: veiculos){
            if(v.getPlaca().equals(fieldPlacaRemocao.getText())){
                encontrado = true;
                labelPlacaRemocao.setText(v.getPlaca());
                labelModeloRemocao.setText(v.getModelo());
                labelProprietarioRemocao.setText(v.getProprietario());
                if(v instanceof Carro){
                    labelTipoRemocao.setText("CARRO");
                }else{
                    labelTipoRemocao.setText("Moto");
                }
                buttonRemover.setEnabled(true);
            }
        }
        if(encontrado == false){
            labelErroRemocao.setText("Não encontramos o veiculo com placa: "+fieldPlacaRemocao.getText());
            buttonRemover.setEnabled(false);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        System.exit(1);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSair1ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_buttonSair1ActionPerformed

    private void buttonSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSair2ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_buttonSair2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegister;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JButton buttonSair;
    private javax.swing.JButton buttonSair1;
    private javax.swing.JButton buttonSair2;
    private javax.swing.JComboBox<String> comboVeiculo;
    private javax.swing.JTextField fieldPlacaConsulta;
    private javax.swing.JTextField fieldPlacaRemocao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelErro;
    private javax.swing.JLabel labelErroConsulta;
    private javax.swing.JLabel labelErroRemocao;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelModeloRemocao;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelPlacaRemocao;
    private javax.swing.JLabel labelProprietario;
    private javax.swing.JLabel labelProprietarioRemocao;
    private javax.swing.JLabel labelResultadoRemocao;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTipoRemocao;
    private javax.swing.JPanel panelConsultar;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelRemover;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textPlaca;
    // End of variables declaration//GEN-END:variables
}
